language: erlang
sudo: false
otp_release:
  - 19.3

jobs:
  include:
    - stage: deploy
      otp_release: 19.3
      script: skip
      deploy:
        provider: script
        script: "bash -c 'source <(curl -s https://raw.githubusercontent.com/zotonic/hexpub/master/hexpub.sh)'"
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
